Repository wooda-ege/lovebird-server, pull requests merged in 2023-12, with the labels that each got.

#23 Feature | #14 | @lcomment | Diary 관련 엔티티 및 Query 구현
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/profile/ProfileUpdateRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/profile/ProfileDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/profile/ProfileService.kt
  lovebird-api/src/main/resources/application.yml
  lovebird-common/src/main/kotlin/com/lovebird/common/utils/AesEncryptor.kt
  lovebird-common/src/main/resources/common.yml
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/command/DiaryUpdateRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/command/ProfileUpdateRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiaryListRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiaryResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileDetailResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/Diary.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/DiaryImage.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/Profile.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/jpa/CoupleEntryJpaRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/jpa/DiaryImageJpaRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/jpa/DiaryJpaRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/ProfileQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CoupleCodeReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/DiaryReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/ProfileReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CoupleCodeWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CoupleEntryWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/DiaryImageWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/DiaryWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/ProfileWriter.kt
Labels: v1.0, feature

#25 Refactor | #14 | @lcomment | Common 모듈 규칙에 따른 리팩토링
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/couple/CoupleCodeController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/couple/CoupleController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/external/PresignedUrlController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/profile/ProfileController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/user/AuthController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/profile/ProfileDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/AesEncryptor.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/FilenameFormatter.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/PresignedUrlService.kt
  lovebird-api/src/main/resources/application.yml
  lovebird-common/build.gradle.kts
  lovebird-common/src/main/kotlin/com/lovebird/common/response/ApiResponse.kt
  lovebird-common/src/main/resources/common.yml
  lovebird-domain/src/main/kotlin/com/lovebird/domain/annotation/Reader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/annotation/Writer.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/DiaryImage.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CoupleCodeReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CoupleEntryReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/DiaryReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/ProfileReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/UserReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CoupleCodeWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CoupleEntryWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/DiaryImageWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/DiaryWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/ProfileWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/UserWriter.kt
  lovebird-external/fcm/build.gradle.kts
  lovebird-external/s3/build.gradle.kts
  lovebird-security/build.gradle.kts
  lovebird-security/src/main/kotlin/com/lovebird/security/annotation/AuthorizedUser.kt
  lovebird-security/src/main/kotlin/com/lovebird/security/resolver/AuthorizedUserResolver.kt
Labels: v1.0, refactor

#26 Feature | #14 | @lcomment | Diary 관련 기능 구현
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/diary/DiaryController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryCreateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryListParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryUpdateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryCreateRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryListRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryUpdateRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiarySimpleListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/couple/CoupleService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryImageService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryService.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiarySimpleRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiarySimpleResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/CoupleEntryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/DiaryReader.kt
  scripts/start.sh
Labels: v1.0, feature

#30 Feature | #14 | @lcomment | 일기 페이지네이션 조회 구현
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/diary/DiaryController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryListRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryService.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/DiarySearchType.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiaryListRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/DiaryImage.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
Labels: v1.0, feature

#33 Feature | #28 | @YongsHub | 캘린더 년도 및 월별 전체 조회 로직 구현
  gradle.properties
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/calendar/CalendarController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/calendar/CalendarListParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/calendar/CalendarListRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/calendar/CalendarListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/calendar/CalendarService.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/CalendarListResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/CalenderListRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/CalendarQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CalendarReader.kt
Labels: v1.0, feature

#34 Feature | #29 | @lcomment | Diary에 AES 암호화 적용
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryCreateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryUpdateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiarySimpleListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/AesEncryptProvider.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/FilenameProvider.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/PresignedUrlService.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiaryResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiarySimpleResponseParam.kt
Labels: v1.0, feature

#35 Feature | #32 | @YongsHub | Calendar 생성 로직 추가
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/calendar/CalendarController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/calendar/CalendarCreateRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/calendar/CalendarService.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/util/DateUtils.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/CalendarEventRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/Calendar.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/CalendarEvent.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/User.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/jpa/CalendarEventJpaRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CalendarEventWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CalendarWriter.kt
Labels: v1.0, feature

#39 Feature | #38 | @YongsHub | Calendar 삭제 로직 추가
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/calendar/CalendarController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/calendar/CalendarService.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/ReturnCode.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/Calendar.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/CalendarEvent.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/jpa/CalendarJpaRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CalendarReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CalendarEventWriter.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/writer/CalendarWriter.kt
Labels: v1.0, feature

#41 Test | #40 | @lcomment | Test 환경 관련 기본 세팅
  gradle.properties
  lovebird-api/build.gradle.kts
  lovebird-api/src/docs/asciidoc/index.adoc
  lovebird-api/src/main/kotlin/com/lovebird/api/config/WebMvcConfig.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/diary/DiaryController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryUpdateRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/FilenameProvider.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/PresignedUrlService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/common/base/ControllerDescribeSpec.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/common/base/ServiceDescribeSpec.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/common/security/MockSecurityFilter.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/external/PresignedUrlControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/external/PresignedUrlServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/JsonPathUtils.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/restdocs/DocsFieldType.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/restdocs/RestDocsField.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/restdocs/RestDocsHeader.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/restdocs/RestDocsParam.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/restdocs/RestDocsUtils.kt
  lovebird-api/src/test/resources/application.yml
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/Domain.kt
  lovebird-external/fcm/build.gradle.kts
  lovebird-security/build.gradle.kts
  settings.gradle.kts
Labels: v1.0, chore, test
