Repository wooda-ege/lovebird-server, pull requests merged in 2024-02, with the labels that each got.

#61 Chore | #59 | @lcomment | develop 서버 배포 관련 설정 및 구성
  .github/workflows/cd-develop.yml
  .github/workflows/ci-develop.yml
  build.gradle.kts
  lovebird-api/src/main/kotlin/com/lovebird/api/config/SecurityConfiguration.kt
  lovebird-api/src/main/resources/application-dev.yml
  lovebird-api/src/main/resources/application.yml
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-domain/src/main/resources/db-dev.yml
  lovebird-external/s3/src/main/resources/s3-dev.yml
  scripts/start.sh
Labels: v1.0, chore

#67 Test | #60 | @YongsHub | Diary Unit Test 작성 및 DiaryService 비즈니스 로직 리팩토링
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryCreateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/diary/DiaryUpdateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryListRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryUpdateRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiaryListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/util/DiaryUtils.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/diary/DiaryServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/CommonTestFixture.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/CoupleTestFixture.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/DiaryTestFixture.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiaryListRequestParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/DiaryReader.kt
Labels: v1.0, fix, refactor, test

#69 Test | #68 | @YongsHub | DiaryController Test 작성 및 Rest Docs 문서 작성
  lovebird-api/src/docs/asciidoc/diary.adoc
  lovebird-api/src/docs/asciidoc/index.adoc
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/diary/DiaryListRequest.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/diary/DiaryControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/diary/DiaryServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/DiaryTestFixture.kt
Labels: v1.0, docs, test

#71 Chore | #70 | @lcomment | Jacoco 및 CodeCov 설정
  .github/workflows/ci-develop.yml
  .github/workflows/ci.yml
  codecov.yml
  lovebird-api/build.gradle.kts
Labels: chore

#72 Chore | #70 | @lcomment | Jacoco 및 CodeCov 오탈자 수정
  .github/workflows/ci.yml
Labels: chore

#74 Feature | #73 | @lcomment | access token 재발급 기능 구현
  lovebird-api/build.gradle.kts
  lovebird-api/src/docs/asciidoc/auth.adoc
  lovebird-api/src/main/kotlin/com/lovebird/api/annotation/RefreshToken.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/common/resolver/RefreshTokenResolver.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/config/WebMvcConfig.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/user/AuthController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/user/AccessTokenResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/JwtProvider.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/user/AuthService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/validator/JwtValidator.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/user/AuthControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/user/AuthServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/AuthTestFixture.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/CommonTestFixture.kt
Labels: v1.0, feature

#76 Fix | #75 | @lcomment | decoder 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/PublicKeyProvider.kt
Labels: v1.0, fix

#78 Fix | #77 | @lcomment | 기념일 엔티티 삭제 및 util 메서드 구현
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/GlobalControllerAdvice.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/profile/ProfileCreateParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/profile/AnniversaryResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/user/SignUpRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/profile/ProfileDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/couple/CoupleCodeService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/profile/ProfileService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/util/ProfileUtils.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/profile/ProfileControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/profile/ProfileServiceTest.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/AnniversaryType.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/ReturnCode.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/util/DateUtils.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileDetailResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/Anniversary.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/DiaryImage.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/Profile.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/entity/User.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/ProfileQueryRepository.kt
Labels: v1.0, fix

#83 Hotfix | #81 | @lcomment | partnerId null 처리 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/couple/CoupleCodeController.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/couple/CoupleCodeControllerTest.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileDetailResponseParam.kt
Labels: v1.0, fix

#84 Hotfix | #81 | @YongsHub | v1.0.1 출시 위해 임시 다이어리 전체 조회 API 추가
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/diary/DiaryController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/diary/DiaryControllerTest.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/DiaryReader.kt
Labels: v1.0, fix

#85 Hotfix | #81 | @YongsHub | v1.0.1 출시 위해 Projection 방식 변경
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/CalendarListResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiarySimpleResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfilePartnerResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileUserResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/CalendarQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/ProfileQueryRepository.kt
Labels: v1.0, fix

#86 Hotfix | #81 | @YongsHub | v1.0.1 출시 위해 Join 방식 변경
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
Labels: v1.0, fix

#87 Hotfix | #81 | @lcomment | where 절 파라미터 수정
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/CoupleEntryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CoupleEntryReader.kt
Labels: v1.0, fix

#88 Hotfix | #81 | @YongsHub | v1.0.1 출시 위해 Query Transform 리팩토링
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/GlobalControllerAdvice.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/diary/DiaryController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiarySimpleListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/diary/DiarySimpleResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/diary/DiaryService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/util/DiaryUtils.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/diary/DiaryControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/diary/DiaryServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/DiaryTestFixture.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/config/QuerydslConfig.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiaryResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/DiarySimpleResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/DiaryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/DiaryReader.kt
Labels: v1.0, fix

#89 Hotfix | #81 | @YongsHub | v1.0.1 출시 위해 Rest Docs 업데이트 및 프로필 조회 nullable 허용
  lovebird-api/src/docs/asciidoc/index.adoc
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/GlobalControllerAdvice.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/profile/ProfileDetailResponse.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/calendar/CalendarControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/profile/ProfileControllerTest.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/ReturnCode.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileDetailResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileUserResponseParam.kt
Labels: v1.0, test
