Repository wooda-ege/lovebird-server, pull requests merged in 2024-03, with the labels that each got.

#90 Feature | #79 | @ lcomment | slack webhook 구성 및 ExceptionHandler에 추가
  .github/workflows/cd-develop.yml
  lovebird-api/build.gradle.kts
  lovebird-api/src/main/kotlin/com/lovebird/api/config/SlackWebhookConfig.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/GlobalControllerAdvice.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/slack/SlackService.kt
  lovebird-api/src/main/resources/application-dev.yml
  lovebird-api/src/main/resources/application-local.yml
  lovebird-api/src/main/resources/application-prod.yml
  lovebird-api/src/main/resources/application.yml
  lovebird-api/src/test/kotlin/com/lovebird/api/common/base/ControllerDescribeSpec.kt
Labels: v1.0, feature

#92 Feature | #91 | @ lcomment | 테스트 관련 API 구현
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/GlobalControllerAdvice.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/user/AuthController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/user/SuperAuthService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/user/AuthControllerTest.kt
Labels: v1.0, feature

#93 Fix | #81 | @lcomment | v1.1 배포를 위한 프로필 관련 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/profile/ProfileDetailResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/profile/ProfileService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/service/profile/ProfileServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/ProfileTestFixture.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfileDetailResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/dto/query/ProfilePartnerResponseParam.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/CoupleEntryQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/ProfileQueryRepository.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/CoupleEntryReader.kt
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/reader/ProfileReader.kt
Labels: v1.0, feature

#97 Hotfix | #81 | @YongsHub | v1.0.1 출시 위해 Calendar nullable 쿼리 수정
  lovebird-domain/src/main/kotlin/com/lovebird/domain/repository/query/CalendarQueryRepository.kt
Labels: v1.0, fix

#98 Hotfix | #81 | @lcomment | presigned url path 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/config/SecurityConfiguration.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/external/PresignedUrlController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/external/DiaryUploadPresignedUrlParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/external/ProfileUploadPresignedUrlParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/external/DiaryUploadPresignedUrlRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/external/ProfileUploadPresignedUrlRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/external/PresignedUrlListResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/PresignedUrlService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/external/PresignedUrlControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/external/PresignedUrlServiceTest.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/util/FilenameUtils.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/util/RandomUtils.kt
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/provider/PresignedUrlProvider.kt
Labels: v1.0, feature

#99 Hotfix | #81 | @lcomment | s3 region 수정
  .github/workflows/cd-develop.yml
  lovebird-external/s3/src/main/resources/s3-dev.yml
Labels: v1.0, fix

#101 Fix | #100 | @lcomment | 토큰 재발급 응답 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/user/AuthController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/user/AccessTokenResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/response/user/RecreateTokenResponse.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/provider/JwtProvider.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/user/AuthService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/user/AuthControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/user/AuthServiceTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/AuthTestFixture.kt
Labels: v1.0, fix

#104 Deploy | #102 | @lcomment | Lovebird 버전 수정
  gradle.properties
  lovebird-api/src/main/resources/static/docs/index.html
Labels: v1.0, chore

#105 Hotfix | #81 | @lcomment | 회원 탈퇴 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/service/couple/CoupleCodeService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/user/AuthDeleteService.kt
  lovebird-api/src/main/resources/static/docs/index.html
Labels: v1.0, fix

#107 Feature | #106 | @lcomment | s3 이미지 업로드 구현
  lovebird-api/src/docs/asciidoc/index.adoc
  lovebird-api/src/docs/asciidoc/s3.adoc
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/external/S3ImageController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/external/DiaryImagesUploadParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/external/ProfileImageUploadParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/external/ProfileImageUploadRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/S3ImageService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/util/ProfileUtils.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/external/S3ImageControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/utils/CommonTestFixture.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/util/FilenameUtils.kt
  lovebird-external/s3/build.gradle.kts
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/dto/request/FileUploadRequest.kt
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/dto/request/FilesUploadRequest.kt
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/dto/response/FileUploadListResponse.kt
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/dto/response/FileUploadResponse.kt
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/service/FileUploadService.kt
Labels: v1.0, feature

#109 Fix | #106 | @lcomment | 이미지 업로드 관련 Request Body 수정
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/external/S3ImageController.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/param/external/ProfileImageUploadParam.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/dto/request/external/ProfileImageUploadRequest.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/PresignedUrlService.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/service/external/S3ImageService.kt
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/external/S3ImageControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/external/PresignedUrlServiceTest.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/util/FilenameUtils.kt
Labels: v1.0, fix

#110 Hotfix | #81 | @lcomment | multipart 테스트 수정
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-api/src/test/kotlin/com/lovebird/api/controller/external/S3ImageControllerTest.kt
  lovebird-api/src/test/kotlin/com/lovebird/api/service/external/PresignedUrlServiceTest.kt
Labels: v1.0, fix

#111 Hotfix | #81 | @lcomment | s3 업로드 파일명 포멧 수정
  lovebird-api/src/main/resources/static/docs/index.html
  lovebird-common/src/main/kotlin/com/lovebird/common/util/FilenameUtils.kt
  lovebird-external/s3/src/main/kotlin/com/lovebird/s3/service/FileUploadService.kt
Labels: v1.0, fix

#112 Hotfix | #81 | @YongsHub | v1.0.1 JWT 예외 상황 분리
  lovebird-api/src/main/kotlin/com/lovebird/api/controller/GlobalControllerAdvice.kt
  lovebird-api/src/main/kotlin/com/lovebird/api/validator/JwtValidator.kt
  lovebird-common/src/main/kotlin/com/lovebird/common/enums/ReturnCode.kt
Labels: v1.0

#113 Hotfix | #81 | @YongsHub | Exception FIlter에 에러 로그 추가
  lovebird-api/src/main/kotlin/com/lovebird/api/common/filter/JwtExceptionFilter.kt
Labels: fix
